<a href="https://colab.research.google.com/github/kaho0/Abstract/blob/main/Week_3_Conceptual_Session_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Basic

In [ ]:
import pandas as pd

In [ ]:
data = [10,20,30,40]
sr = pd.Series(data, index=['x','y','z','zz'])
print(sr)
print(sr.loc['x'])
print(sr.iloc[0])

x     10
y     20
z     30
zz    40
dtype: int64
10
10

In [ ]:
print(sr['x'])

10

In [ ]:
data = {'a': 10, 'b':20, 'c': 30}
sr = pd.Series(data)
sr

a    10
b    20
c    30
dtype: int64

In [ ]:
print(sr['a'])
print(sr[1])
print(sr[['a', 'c']])

10
20
a    10
c    30
dtype: int64

/tmp/ipython-input-258712495.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(sr[1])

In [ ]:
print(sr.loc[['a', 'c']])
print(sr.loc['a'])

a    10
c    30
dtype: int64
10

In [ ]:
print(sr.iloc[1])

20

In [ ]:
sr

x     10
y     20
z     30
zz    40
dtype: int64

In [ ]:
print(sr['x':'z']) # loc = Last tao nibe
print(sr[0:2]) # iloc = Last er ager ta porjonto nibe

x    10
y    20
z    30
dtype: int64
x    10
y    20
dtype: int64

In [ ]:
print(sr.loc['x':'z'])
print(sr.iloc[0:2])

x    10
y    20
z    30
dtype: int64
x    10
y    20
dtype: int64

In [ ]:
print(sr.get('x'))
print(sr.get('a',50))

10
50

In [ ]:
## Dataframe
series1 = pd.Series([10,20,30,40], index=[2, 3,4,5])
series2 = pd.Series(['A','B','C','D'], index=[5, 4, 3, 2])

df = pd.DataFrame({'Numbers': series1, 'Letter':series2})
df

   Numbers Letter
2       10      D
3       20      C
4       30      B
5       40      A

In [ ]:
## Dataframa 2 Dictionary of list

data1 = {
    'Name': ['Rakib', 'Tamim', 'Yasin'],
    'Age': [25, 24, 27],
    'City': ['Chittagong', 'Dhaka', 'Barishal']
}
df = pd.DataFrame(data1)
df

    Name  Age        City
0  Rakib   25  Chittagong
1  Tamim   24       Dhaka
2  Yasin   27    Barishal

In [ ]:
## Dataframa 3 List of dictionary
data3 = [
    {'Name': 'Rakib', 'Age': 25, 'City': "Chittagong"},
    {'Name': 'Rakib2', 'Age': 25, 'City': "Chittagong"},
    {'Name': 'Rakib3', 'Age': 25, 'City': "Chittagong"},
    {'Name': 'Rakib3', 'Age': 25, 'City': "Chittagong"},
]
df2 = pd.DataFrame(data3, index=['a','b','c','d'])
df2

     Name  Age        City
a   Rakib   25  Chittagong
b  Rakib2   25  Chittagong
c  Rakib3   25  Chittagong
d  Rakib3   25  Chittagong

In [ ]:
print(df2.loc['a'])

Name         Rakib
Age             25
City    Chittagong
Name: a, dtype: object

In [ ]:
print(df2.iloc[1])

Name        Rakib2
Age             25
City    Chittagong
Name: b, dtype: object

In [ ]:
print(df2.iloc[0:3])

     Name  Age        City
a   Rakib   25  Chittagong
b  Rakib2   25  Chittagong
c  Rakib3   25  Chittagong

In [ ]:
print(df2.loc['a':'c'])

     Name  Age        City
a   Rakib   25  Chittagong
b  Rakib2   25  Chittagong
c  Rakib3   25  Chittagong

In [ ]:
print(df2.iat[1,0])

Rakib2

In [ ]:
## Add a Column
df2['Salary']=[1000,2500,5000,4500]
df2

     Name  Age        City  Salary
a   Rakib   25  Chittagong    1000
b  Rakib2   25  Chittagong    2500
c  Rakib3   25  Chittagong    5000
d  Rakib3   25  Chittagong    4500

In [ ]:
df2['Salary']

a    1000
b    2500
c    5000
d    4500
Name: Salary, dtype: int64

In [ ]:
df2

     Name  Age        City  Salary
a   Rakib   25  Chittagong    1000
b  Rakib2   25  Chittagong    2500
c  Rakib3   25  Chittagong    5000
d  Rakib3   25  Chittagong    4500

axis : {0 or 'index', 1 or 'columns'}, default 0
    Whether to drop labels from the index (0 or 'index') or
columns (1 or 'columns').

In [ ]:
df2.drop('Salary', axis=1, inplace=True)

In [ ]:
df2

     Name  Age        City
a   Rakib   25  Chittagong
b  Rakib2   25  Chittagong
c  Rakib3   25  Chittagong
d  Rakib3   25  Chittagong

In [ ]:
df2.drop('a', axis=0)

     Name  Age        City
b  Rakib2   25  Chittagong
c  Rakib3   25  Chittagong
d  Rakib3   25  Chittagong

In [ ]:
df2

     Name  Age        City
a   Rakib   25  Chittagong
b  Rakib2   25  Chittagong
c  Rakib3   25  Chittagong
d  Rakib3   25  Chittagong

In [ ]:
df2['Age'] = df2['Age']+10

In [ ]:
df2

     Name  Age        City
a   Rakib   55  Chittagong
b  Rakib2   55  Chittagong
c  Rakib3   55  Chittagong
d  Rakib3   55  Chittagong

# Read from csv
Download link https://drive.google.com/file/d/1_MS71FKXVYlOyY25KUqPhV8Wro4Btl4y/view?usp=sharing

In [ ]:
df = pd.read_csv('data.csv')

In [ ]:
df

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    NaN   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    NaN  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-01-18        C    NaN  Product1  108.0   West
18  2023-01-19        A   31.0  Product2  578.0   West
19  2023-01-20        A   59.0  Product1  736.0   East
20  2023-01-21        C   82.0  Product3  606.0  South
21  2023-01-22        C   37.0  Product2  992.0  South
22  2023-01-23        B   62.0  Product3  942.0  North
23  2023-01-24        C   92.0  Product2  342.0   West
24  2023-01-25        A   24.0  Product2  458.0   East
25  2023-01-26        C   95.0  Product1  584.0   West
26  2023-01-27        C   71.0  Product2  619.0  North
27  2023-01-28        C   56.0  Product2  224.0  North
28  2023-01-29        B    NaN  Product3  617.0  North
29  2023-01-30        C   51.0  Product2  737.0  South
30  2023-01-31        B   50.0  Product3  735.0   West
31  2023-02-01        A   17.0  Product2  189.0   West
32  2023-02-02        B   63.0  Product3  338.0  South
33  2023-02-03        C   27.0  Product3    NaN   East
34  2023-02-04        C   70.0  Product3  669.0   West
35  2023-02-05        B   60.0  Product2    NaN   West
36  2023-02-06        C   36.0  Product3  177.0   East
37  2023-02-07        C    2.0  Product1    NaN  North
38  2023-02-08        C   94.0  Product1  408.0  South
39  2023-02-09        A   62.0  Product1  155.0   West
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [ ]:
df.head()

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [ ]:
df.tail()

          Date Category  Value   Product  Sales Region
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [ ]:
df.describe()

           Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

In [ ]:
df.dtypes

Date         object
Category     object
Value       float64
Product      object
Sales       float64
Region       object
dtype: object

In [ ]:
df.isnull()

     Date  Category  Value  Product  Sales  Region
0   False     False  False    False  False   False
1   False     False  False    False  False   False
2   False     False  False    False  False   False
3   False     False  False    False  False   False
4   False     False  False    False  False   False
5   False     False  False    False  False   False
6   False     False  False    False  False   False
7   False     False  False    False  False   False
8   False     False  False    False  False   False
9   False     False  False    False  False   False
10  False     False  False    False  False   False
11  False     False  False    False   True   False
12  False     False  False    False  False   False
13  False     False  False    False  False   False
14  False     False  False    False  False   False
15  False     False   True    False  False   False
16  False     False  False    False  False   False
17  False     False   True    False  False   False
18  False     False  False    False  False   False
19  False     False  False    False  False   False
20  False     False  False    False  False   False
21  False     False  False    False  False   False
22  False     False  False    False  False   False
23  False     False  False    False  False   False
24  False     False  False    False  False   False
25  False     False  False    False  False   False
26  False     False  False    False  False   False
27  False     False  False    False  False   False
28  False     False   True    False  False   False
29  False     False  False    False  False   False
30  False     False  False    False  False   False
31  False     False  False    False  False   False
32  False     False  False    False  False   False
33  False     False  False    False   True   False
34  False     False  False    False  False   False
35  False     False  False    False   True   False
36  False     False  False    False  False   False
37  False     False  False    False   True   False
38  False     False  False    False  False   False
39  False     False  False    False  False   False
40  False     False  False    False  False   False
41  False     False  False    False  False   False
42  False     False  False    False  False   False
43  False     False  False    False  False   False
44  False     False  False    False  False   False
45  False     False  False    False  False   False
46  False     False  False    False  False   False
47  False     False  False    False  False   False
48  False     False  False    False  False   False
49  False     False  False    False  False   False

In [ ]:
df.isnull().sum()

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [ ]:
df.fillna(0)

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    0.0   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    0.0  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-01-18        C    0.0  Product1  108.0   West
18  2023-01-19        A   31.0  Product2  578.0   West
19  2023-01-20        A   59.0  Product1  736.0   East
20  2023-01-21        C   82.0  Product3  606.0  South
21  2023-01-22        C   37.0  Product2  992.0  South
22  2023-01-23        B   62.0  Product3  942.0  North
23  2023-01-24        C   92.0  Product2  342.0   West
24  2023-01-25        A   24.0  Product2  458.0   East
25  2023-01-26        C   95.0  Product1  584.0   West
26  2023-01-27        C   71.0  Product2  619.0  North
27  2023-01-28        C   56.0  Product2  224.0  North
28  2023-01-29        B    0.0  Product3  617.0  North
29  2023-01-30        C   51.0  Product2  737.0  South
30  2023-01-31        B   50.0  Product3  735.0   West
31  2023-02-01        A   17.0  Product2  189.0   West
32  2023-02-02        B   63.0  Product3  338.0  South
33  2023-02-03        C   27.0  Product3    0.0   East
34  2023-02-04        C   70.0  Product3  669.0   West
35  2023-02-05        B   60.0  Product2    0.0   West
36  2023-02-06        C   36.0  Product3  177.0   East
37  2023-02-07        C    2.0  Product1    0.0  North
38  2023-02-08        C   94.0  Product1  408.0  South
39  2023-02-09        A   62.0  Product1  155.0   West
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [ ]:
df['Sales_NOT_NAN'] = df['Sales'].fillna(df['Sales'].mean())
df

          Date Category  Value   Product  Sales Region  Sales_NOT_NAN
0   2023-01-01        A   28.0  Product1  754.0   East     754.000000
1   2023-01-02        B   39.0  Product3  110.0  North     110.000000
2   2023-01-03        C   32.0  Product2  398.0   East     398.000000
3   2023-01-04        B    8.0  Product1  522.0   East     522.000000
4   2023-01-05        B   26.0  Product3  869.0  North     869.000000
5   2023-01-06        B   54.0  Product3  192.0   West     192.000000
6   2023-01-07        A   16.0  Product1  936.0   East     936.000000
7   2023-01-08        C   89.0  Product1  488.0   West     488.000000
8   2023-01-09        C   37.0  Product3  772.0   West     772.000000
9   2023-01-10        A   22.0  Product2  834.0   West     834.000000
10  2023-01-11        B    7.0  Product1  842.0  North     842.000000
11  2023-01-12        B   60.0  Product2    NaN   West     557.130435
12  2023-01-13        A   70.0  Product3  628.0  South     628.000000
13  2023-01-14        A   69.0  Product1  423.0   East     423.000000
14  2023-01-15        A   47.0  Product2  893.0   West     893.000000
15  2023-01-16        C    NaN  Product1  895.0  North     895.000000
16  2023-01-17        C   93.0  Product2  511.0  South     511.000000
17  2023-01-18        C    NaN  Product1  108.0   West     108.000000
18  2023-01-19        A   31.0  Product2  578.0   West     578.000000
19  2023-01-20        A   59.0  Product1  736.0   East     736.000000
20  2023-01-21        C   82.0  Product3  606.0  South     606.000000
21  2023-01-22        C   37.0  Product2  992.0  South     992.000000
22  2023-01-23        B   62.0  Product3  942.0  North     942.000000
23  2023-01-24        C   92.0  Product2  342.0   West     342.000000
24  2023-01-25        A   24.0  Product2  458.0   East     458.000000
25  2023-01-26        C   95.0  Product1  584.0   West     584.000000
26  2023-01-27        C   71.0  Product2  619.0  North     619.000000
27  2023-01-28        C   56.0  Product2  224.0  North     224.000000
28  2023-01-29        B    NaN  Product3  617.0  North     617.000000
29  2023-01-30        C   51.0  Product2  737.0  South     737.000000
30  2023-01-31        B   50.0  Product3  735.0   West     735.000000
31  2023-02-01        A   17.0  Product2  189.0   West     189.000000
32  2023-02-02        B   63.0  Product3  338.0  South     338.000000
33  2023-02-03        C   27.0  Product3    NaN   East     557.130435
34  2023-02-04        C   70.0  Product3  669.0   West     669.000000
35  2023-02-05        B   60.0  Product2    NaN   West     557.130435
36  2023-02-06        C   36.0  Product3  177.0   East     177.000000
37  2023-02-07        C    2.0  Product1    NaN  North     557.130435
38  2023-02-08        C   94.0  Product1  408.0  South     408.000000
39  2023-02-09        A   62.0  Product1  155.0   West     155.000000
40  2023-02-10        B   15.0  Product1  578.0   East     578.000000
41  2023-02-11        C   97.0  Product1  256.0   East     256.000000
42  2023-02-12        A   93.0  Product3  164.0   West     164.000000
43  2023-02-13        A   43.0  Product3  949.0   East     949.000000
44  2023-02-14        A   96.0  Product3  830.0   East     830.000000
45  2023-02-15        B   99.0  Product2  599.0   West     599.000000
46  2023-02-16        B    6.0  Product1  938.0  South     938.000000
47  2023-02-17        B   69.0  Product3  143.0   West     143.000000
48  2023-02-18        C   65.0  Product3  182.0  North     182.000000
49  2023-02-19        C   11.0  Product3  708.0  North     708.000000

In [ ]:
df = df.rename(columns={'Sales_NOT_NAN':'New_Sales'})
df

          Date Category  Value   Product  Sales Region   New_Sales
0   2023-01-01        A   28.0  Product1  754.0   East  754.000000
1   2023-01-02        B   39.0  Product3  110.0  North  110.000000
2   2023-01-03        C   32.0  Product2  398.0   East  398.000000
3   2023-01-04        B    8.0  Product1  522.0   East  522.000000
4   2023-01-05        B   26.0  Product3  869.0  North  869.000000
5   2023-01-06        B   54.0  Product3  192.0   West  192.000000
6   2023-01-07        A   16.0  Product1  936.0   East  936.000000
7   2023-01-08        C   89.0  Product1  488.0   West  488.000000
8   2023-01-09        C   37.0  Product3  772.0   West  772.000000
9   2023-01-10        A   22.0  Product2  834.0   West  834.000000
10  2023-01-11        B    7.0  Product1  842.0  North  842.000000
11  2023-01-12        B   60.0  Product2    NaN   West  557.130435
12  2023-01-13        A   70.0  Product3  628.0  South  628.000000
13  2023-01-14        A   69.0  Product1  423.0   East  423.000000
14  2023-01-15        A   47.0  Product2  893.0   West  893.000000
15  2023-01-16        C    NaN  Product1  895.0  North  895.000000
16  2023-01-17        C   93.0  Product2  511.0  South  511.000000
17  2023-01-18        C    NaN  Product1  108.0   West  108.000000
18  2023-01-19        A   31.0  Product2  578.0   West  578.000000
19  2023-01-20        A   59.0  Product1  736.0   East  736.000000
20  2023-01-21        C   82.0  Product3  606.0  South  606.000000
21  2023-01-22        C   37.0  Product2  992.0  South  992.000000
22  2023-01-23        B   62.0  Product3  942.0  North  942.000000
23  2023-01-24        C   92.0  Product2  342.0   West  342.000000
24  2023-01-25        A   24.0  Product2  458.0   East  458.000000
25  2023-01-26        C   95.0  Product1  584.0   West  584.000000
26  2023-01-27        C   71.0  Product2  619.0  North  619.000000
27  2023-01-28        C   56.0  Product2  224.0  North  224.000000
28  2023-01-29        B    NaN  Product3  617.0  North  617.000000
29  2023-01-30        C   51.0  Product2  737.0  South  737.000000
30  2023-01-31        B   50.0  Product3  735.0   West  735.000000
31  2023-02-01        A   17.0  Product2  189.0   West  189.000000
32  2023-02-02        B   63.0  Product3  338.0  South  338.000000
33  2023-02-03        C   27.0  Product3    NaN   East  557.130435
34  2023-02-04        C   70.0  Product3  669.0   West  669.000000
35  2023-02-05        B   60.0  Product2    NaN   West  557.130435
36  2023-02-06        C   36.0  Product3  177.0   East  177.000000
37  2023-02-07        C    2.0  Product1    NaN  North  557.130435
38  2023-02-08        C   94.0  Product1  408.0  South  408.000000
39  2023-02-09        A   62.0  Product1  155.0   West  155.000000
40  2023-02-10        B   15.0  Product1  578.0   East  578.000000
41  2023-02-11        C   97.0  Product1  256.0   East  256.000000
42  2023-02-12        A   93.0  Product3  164.0   West  164.000000
43  2023-02-13        A   43.0  Product3  949.0   East  949.000000
44  2023-02-14        A   96.0  Product3  830.0   East  830.000000
45  2023-02-15        B   99.0  Product2  599.0   West  599.000000
46  2023-02-16        B    6.0  Product1  938.0  South  938.000000
47  2023-02-17        B   69.0  Product3  143.0   West  143.000000
48  2023-02-18        C   65.0  Product3  182.0  North  182.000000
49  2023-02-19        C   11.0  Product3  708.0  North  708.000000

In [ ]:
df['Value_2x']= df['Value'].apply(lambda x: x*2)
df

          Date Category  Value   Product  Sales Region   New_Sales  Value_2x
0   2023-01-01        A   28.0  Product1  754.0   East  754.000000      56.0
1   2023-01-02        B   39.0  Product3  110.0  North  110.000000      78.0
2   2023-01-03        C   32.0  Product2  398.0   East  398.000000      64.0
3   2023-01-04        B    8.0  Product1  522.0   East  522.000000      16.0
4   2023-01-05        B   26.0  Product3  869.0  North  869.000000      52.0
5   2023-01-06        B   54.0  Product3  192.0   West  192.000000     108.0
6   2023-01-07        A   16.0  Product1  936.0   East  936.000000      32.0
7   2023-01-08        C   89.0  Product1  488.0   West  488.000000     178.0
8   2023-01-09        C   37.0  Product3  772.0   West  772.000000      74.0
9   2023-01-10        A   22.0  Product2  834.0   West  834.000000      44.0
10  2023-01-11        B    7.0  Product1  842.0  North  842.000000      14.0
11  2023-01-12        B   60.0  Product2    NaN   West  557.130435     120.0
12  2023-01-13        A   70.0  Product3  628.0  South  628.000000     140.0
13  2023-01-14        A   69.0  Product1  423.0   East  423.000000     138.0
14  2023-01-15        A   47.0  Product2  893.0   West  893.000000      94.0
15  2023-01-16        C    NaN  Product1  895.0  North  895.000000       NaN
16  2023-01-17        C   93.0  Product2  511.0  South  511.000000     186.0
17  2023-01-18        C    NaN  Product1  108.0   West  108.000000       NaN
18  2023-01-19        A   31.0  Product2  578.0   West  578.000000      62.0
19  2023-01-20        A   59.0  Product1  736.0   East  736.000000     118.0
20  2023-01-21        C   82.0  Product3  606.0  South  606.000000     164.0
21  2023-01-22        C   37.0  Product2  992.0  South  992.000000      74.0
22  2023-01-23        B   62.0  Product3  942.0  North  942.000000     124.0
23  2023-01-24        C   92.0  Product2  342.0   West  342.000000     184.0
24  2023-01-25        A   24.0  Product2  458.0   East  458.000000      48.0
25  2023-01-26        C   95.0  Product1  584.0   West  584.000000     190.0
26  2023-01-27        C   71.0  Product2  619.0  North  619.000000     142.0
27  2023-01-28        C   56.0  Product2  224.0  North  224.000000     112.0
28  2023-01-29        B    NaN  Product3  617.0  North  617.000000       NaN
29  2023-01-30        C   51.0  Product2  737.0  South  737.000000     102.0
30  2023-01-31        B   50.0  Product3  735.0   West  735.000000     100.0
31  2023-02-01        A   17.0  Product2  189.0   West  189.000000      34.0
32  2023-02-02        B   63.0  Product3  338.0  South  338.000000     126.0
33  2023-02-03        C   27.0  Product3    NaN   East  557.130435      54.0
34  2023-02-04        C   70.0  Product3  669.0   West  669.000000     140.0
35  2023-02-05        B   60.0  Product2    NaN   West  557.130435     120.0
36  2023-02-06        C   36.0  Product3  177.0   East  177.000000      72.0
37  2023-02-07        C    2.0  Product1    NaN  North  557.130435       4.0
38  2023-02-08        C   94.0  Product1  408.0  South  408.000000     188.0
39  2023-02-09        A   62.0  Product1  155.0   West  155.000000     124.0
40  2023-02-10        B   15.0  Product1  578.0   East  578.000000      30.0
41  2023-02-11        C   97.0  Product1  256.0   East  256.000000     194.0
42  2023-02-12        A   93.0  Product3  164.0   West  164.000000     186.0
43  2023-02-13        A   43.0  Product3  949.0   East  949.000000      86.0
44  2023-02-14        A   96.0  Product3  830.0   East  830.000000     192.0
45  2023-02-15        B   99.0  Product2  599.0   West  599.000000     198.0
46  2023-02-16        B    6.0  Product1  938.0  South  938.000000      12.0
47  2023-02-17        B   69.0  Product3  143.0   West  143.000000     138.0
48  2023-02-18        C   65.0  Product3  182.0  North  182.000000     130.0
49  2023-02-19        C   11.0  Product3  708.0  North  708.000000      22.0

In [ ]:
df = df.sort_values(['Value_2x', 'Sales'], ascending=True)
df

          Date Category  Value   Product  Sales Region   New_Sales  Value_2x
37  2023-02-07        C    2.0  Product1    NaN  North  557.130435       4.0
46  2023-02-16        B    6.0  Product1  938.0  South  938.000000      12.0
10  2023-01-11        B    7.0  Product1  842.0  North  842.000000      14.0
3   2023-01-04        B    8.0  Product1  522.0   East  522.000000      16.0
49  2023-02-19        C   11.0  Product3  708.0  North  708.000000      22.0
40  2023-02-10        B   15.0  Product1  578.0   East  578.000000      30.0
6   2023-01-07        A   16.0  Product1  936.0   East  936.000000      32.0
31  2023-02-01        A   17.0  Product2  189.0   West  189.000000      34.0
9   2023-01-10        A   22.0  Product2  834.0   West  834.000000      44.0
24  2023-01-25        A   24.0  Product2  458.0   East  458.000000      48.0
4   2023-01-05        B   26.0  Product3  869.0  North  869.000000      52.0
33  2023-02-03        C   27.0  Product3    NaN   East  557.130435      54.0
0   2023-01-01        A   28.0  Product1  754.0   East  754.000000      56.0
18  2023-01-19        A   31.0  Product2  578.0   West  578.000000      62.0
2   2023-01-03        C   32.0  Product2  398.0   East  398.000000      64.0
36  2023-02-06        C   36.0  Product3  177.0   East  177.000000      72.0
8   2023-01-09        C   37.0  Product3  772.0   West  772.000000      74.0
21  2023-01-22        C   37.0  Product2  992.0  South  992.000000      74.0
1   2023-01-02        B   39.0  Product3  110.0  North  110.000000      78.0
43  2023-02-13        A   43.0  Product3  949.0   East  949.000000      86.0
14  2023-01-15        A   47.0  Product2  893.0   West  893.000000      94.0
30  2023-01-31        B   50.0  Product3  735.0   West  735.000000     100.0
29  2023-01-30        C   51.0  Product2  737.0  South  737.000000     102.0
5   2023-01-06        B   54.0  Product3  192.0   West  192.000000     108.0
27  2023-01-28        C   56.0  Product2  224.0  North  224.000000     112.0
19  2023-01-20        A   59.0  Product1  736.0   East  736.000000     118.0
35  2023-02-05        B   60.0  Product2    NaN   West  557.130435     120.0
11  2023-01-12        B   60.0  Product2    NaN   West  557.130435     120.0
39  2023-02-09        A   62.0  Product1  155.0   West  155.000000     124.0
22  2023-01-23        B   62.0  Product3  942.0  North  942.000000     124.0
32  2023-02-02        B   63.0  Product3  338.0  South  338.000000     126.0
48  2023-02-18        C   65.0  Product3  182.0  North  182.000000     130.0
47  2023-02-17        B   69.0  Product3  143.0   West  143.000000     138.0
13  2023-01-14        A   69.0  Product1  423.0   East  423.000000     138.0
12  2023-01-13        A   70.0  Product3  628.0  South  628.000000     140.0
34  2023-02-04        C   70.0  Product3  669.0   West  669.000000     140.0
26  2023-01-27        C   71.0  Product2  619.0  North  619.000000     142.0
20  2023-01-21        C   82.0  Product3  606.0  South  606.000000     164.0
7   2023-01-08        C   89.0  Product1  488.0   West  488.000000     178.0
23  2023-01-24        C   92.0  Product2  342.0   West  342.000000     184.0
42  2023-02-12        A   93.0  Product3  164.0   West  164.000000     186.0
16  2023-01-17        C   93.0  Product2  511.0  South  511.000000     186.0
38  2023-02-08        C   94.0  Product1  408.0  South  408.000000     188.0
25  2023-01-26        C   95.0  Product1  584.0   West  584.000000     190.0
44  2023-02-14        A   96.0  Product3  830.0   East  830.000000     192.0
41  2023-02-11        C   97.0  Product1  256.0   East  256.000000     194.0
45  2023-02-15        B   99.0  Product2  599.0   West  599.000000     198.0
17  2023-01-18        C    NaN  Product1  108.0   West  108.000000       NaN
28  2023-01-29        B    NaN  Product3  617.0  North  617.000000       NaN
15  2023-01-16        C    NaN  Product1  895.0  North  895.000000       NaN

In [ ]:
df[ (df['Category']=='A') & (df['Region']=='East')]

          Date Category  Value   Product  Sales Region  New_Sales  Value_2x
6   2023-01-07        A   16.0  Product1  936.0   East      936.0      32.0
24  2023-01-25        A   24.0  Product2  458.0   East      458.0      48.0
0   2023-01-01        A   28.0  Product1  754.0   East      754.0      56.0
43  2023-02-13        A   43.0  Product3  949.0   East      949.0      86.0
19  2023-01-20        A   59.0  Product1  736.0   East      736.0     118.0
13  2023-01-14        A   69.0  Product1  423.0   East      423.0     138.0
44  2023-02-14        A   96.0  Product3  830.0   East      830.0     192.0

In [ ]:
df[ ~(df['Category']=='A')]

          Date Category  Value   Product  Sales Region   New_Sales  Value_2x
37  2023-02-07        C    2.0  Product1    NaN  North  557.130435       4.0
46  2023-02-16        B    6.0  Product1  938.0  South  938.000000      12.0
10  2023-01-11        B    7.0  Product1  842.0  North  842.000000      14.0
3   2023-01-04        B    8.0  Product1  522.0   East  522.000000      16.0
49  2023-02-19        C   11.0  Product3  708.0  North  708.000000      22.0
40  2023-02-10        B   15.0  Product1  578.0   East  578.000000      30.0
4   2023-01-05        B   26.0  Product3  869.0  North  869.000000      52.0
33  2023-02-03        C   27.0  Product3    NaN   East  557.130435      54.0
2   2023-01-03        C   32.0  Product2  398.0   East  398.000000      64.0
36  2023-02-06        C   36.0  Product3  177.0   East  177.000000      72.0
8   2023-01-09        C   37.0  Product3  772.0   West  772.000000      74.0
21  2023-01-22        C   37.0  Product2  992.0  South  992.000000      74.0
1   2023-01-02        B   39.0  Product3  110.0  North  110.000000      78.0
30  2023-01-31        B   50.0  Product3  735.0   West  735.000000     100.0
29  2023-01-30        C   51.0  Product2  737.0  South  737.000000     102.0
5   2023-01-06        B   54.0  Product3  192.0   West  192.000000     108.0
27  2023-01-28        C   56.0  Product2  224.0  North  224.000000     112.0
35  2023-02-05        B   60.0  Product2    NaN   West  557.130435     120.0
11  2023-01-12        B   60.0  Product2    NaN   West  557.130435     120.0
22  2023-01-23        B   62.0  Product3  942.0  North  942.000000     124.0
32  2023-02-02        B   63.0  Product3  338.0  South  338.000000     126.0
48  2023-02-18        C   65.0  Product3  182.0  North  182.000000     130.0
47  2023-02-17        B   69.0  Product3  143.0   West  143.000000     138.0
34  2023-02-04        C   70.0  Product3  669.0   West  669.000000     140.0
26  2023-01-27        C   71.0  Product2  619.0  North  619.000000     142.0
20  2023-01-21        C   82.0  Product3  606.0  South  606.000000     164.0
7   2023-01-08        C   89.0  Product1  488.0   West  488.000000     178.0
23  2023-01-24        C   92.0  Product2  342.0   West  342.000000     184.0
16  2023-01-17        C   93.0  Product2  511.0  South  511.000000     186.0
38  2023-02-08        C   94.0  Product1  408.0  South  408.000000     188.0
25  2023-01-26        C   95.0  Product1  584.0   West  584.000000     190.0
41  2023-02-11        C   97.0  Product1  256.0   East  256.000000     194.0
45  2023-02-15        B   99.0  Product2  599.0   West  599.000000     198.0
17  2023-01-18        C    NaN  Product1  108.0   West  108.000000       NaN
28  2023-01-29        B    NaN  Product3  617.0  North  617.000000       NaN
15  2023-01-16        C    NaN  Product1  895.0  North  895.000000       NaN

In [ ]:
arr = df[ df['Category']=='B']
print(arr)
print(type(arr))
arr = arr['Value'].unique()
print(arr)
print(type(arr))

          Date Category  Value   Product  Sales Region   New_Sales  Value_2x
46  2023-02-16        B    6.0  Product1  938.0  South  938.000000      12.0
10  2023-01-11        B    7.0  Product1  842.0  North  842.000000      14.0
3   2023-01-04        B    8.0  Product1  522.0   East  522.000000      16.0
40  2023-02-10        B   15.0  Product1  578.0   East  578.000000      30.0
4   2023-01-05        B   26.0  Product3  869.0  North  869.000000      52.0
1   2023-01-02        B   39.0  Product3  110.0  North  110.000000      78.0
30  2023-01-31        B   50.0  Product3  735.0   West  735.000000     100.0
5   2023-01-06        B   54.0  Product3  192.0   West  192.000000     108.0
35  2023-02-05        B   60.0  Product2    NaN   West  557.130435     120.0
11  2023-01-12        B   60.0  Product2    NaN   West  557.130435     120.0
22  2023-01-23        B   62.0  Product3  942.0  North  942.000000     124.0
32  2023-02-02        B   63.0  Product3  338.0  South  338.000000     126.0
47  2023-02-17        B   69.0  Product3  143.0   West  143.000000     138.0
45  2023-02-15        B   99.0  Product2  599.0   West  599.000000     198.0
28  2023-01-29        B    NaN  Product3  617.0  North  617.000000       NaN
<class 'pandas.core.frame.DataFrame'>
[ 6.  7.  8. 15. 26. 39. 50. 54. 60. 62. 63. 69. 99. nan]
<class 'numpy.ndarray'>

In [ ]:
arr = df[ df['Category']=='B']
arr.drop_duplicates(subset=['Value'])

          Date Category  Value   Product  Sales Region   New_Sales  Value_2x
46  2023-02-16        B    6.0  Product1  938.0  South  938.000000      12.0
10  2023-01-11        B    7.0  Product1  842.0  North  842.000000      14.0
3   2023-01-04        B    8.0  Product1  522.0   East  522.000000      16.0
40  2023-02-10        B   15.0  Product1  578.0   East  578.000000      30.0
4   2023-01-05        B   26.0  Product3  869.0  North  869.000000      52.0
1   2023-01-02        B   39.0  Product3  110.0  North  110.000000      78.0
30  2023-01-31        B   50.0  Product3  735.0   West  735.000000     100.0
5   2023-01-06        B   54.0  Product3  192.0   West  192.000000     108.0
35  2023-02-05        B   60.0  Product2    NaN   West  557.130435     120.0
22  2023-01-23        B   62.0  Product3  942.0  North  942.000000     124.0
32  2023-02-02        B   63.0  Product3  338.0  South  338.000000     126.0
47  2023-02-17        B   69.0  Product3  143.0   West  143.000000     138.0
45  2023-02-15        B   99.0  Product2  599.0   West  599.000000     198.0
28  2023-01-29        B    NaN  Product3  617.0  North  617.000000       NaN

# Problem Solving (LeetCode)

https://leetcode.com/problems/customers-who-never-order/description/?envType=study-plan-v2&envId=30-days-of-pandas&lang=pythondata

In [ ]:
import pandas as pd

def find_customers(customers: pd.DataFrame, orders: pd.DataFrame) -> pd.DataFrame:
    arr = customers[ ~customers['id'].isin(orders['customerId'])]
    arr2 = arr[['name']].rename(columns={'name':'Customers'})
    return arr2

https://leetcode.com/problems/article-views-i/?envType=study-plan-v2&envId=30-days-of-pandas&lang=pythondata

In [ ]:
import pandas as pd

def article_views(views: pd.DataFrame) -> pd.DataFrame:
    arr = views[ views['author_id']==views['viewer_id']  ]

    arr2 = arr['author_id'].unique()
    arr2 = sorted(arr2)

    return pd.DataFrame({'id':arr2})